### ISSUE TITLE
Social SignIn needed

### ISSUE THREAD

**Issue by krsnaa** [aws-samples/create-react-app-auth-amplify#1]
It would be great to extend this app to incorporate social signIn since it is the most widely used form of authentication and from looking at the forums, it appears that a LOT of people are having issues incorporating it in their apps.

Something as simple as incorporating FB, Google and Twitter seems super laborious and error prone from reading the Amplify docs, which is also super cluttered and all over the place.

Something along the lines of https://fir-ui-demo-84a6c.firebaseapp.com would be much appreciated.

**Comment by dabit3** [comment]
@krsnaa thanks for chiming in on this. Agreed. I'll start working on something & ping this issue when it's ready to go.

**Comment by swaminator** [comment]
Hey @krsnaa thanks for the feedback. @dabit3 created this awesome post: https://dev.to/dabit3/the-complete-guide-to-user-authentication-with-the-amplify-framework-2inh. Hope it helps!
