### ISSUE TITLE
amplify init not asking "Do you want to use an existing environment?"

### ISSUE THREAD

**Issue by kimfucious** [aws-samples/create-react-app-auth-amplify#15]
Amplify CLI version: 4.13.1

In brief, I'm trying to provision an existing backend (react app) to a new react native app.

Following the docs [here](https://github.com/aws-samples/create-react-app-auth-amplify/blob/master/README.md#run-locally-with-the-amplify-cli), I've performed steps 1-3 to add the env to a local project (on a different machine from where the site was initially built).

In step 3 (the second one, as there are 2 of them), its shows a prompt: `Do you want to use an existing environment? Yes`.

This prompt does not show.  Instead, the prompts are:

```console
? Enter a name for the project
? Enter a name for the environment
? Choose your default editor: (Use arrow keys)
```
Did I miss a step, have I lost the plot, or have things changed since this doc was written?

Thanks

**Comment by Jean-bapt-18-154** [comment]
A bit late but I just faced the same problem. When you go to your app console, you'll see in the backend environments panels the command to init from the current appId
`$ amplify init --appId YOUR_APP_ID`
