### ISSUE TITLE
Aws - Amplify frame work interaction voice enabled not working with Lex bot

### ISSUE THREAD

**Issue by rushesh** [aws-samples/create-react-app-auth-amplify#18]
I am using aws-amplify interaction : https://aws-amplify.github.io/docs/
Interaction code is :

 <ChatBot
          title="My Bot"
          theme={myTheme}
          botName="OrderFlowers"
          welcomeMessage="Welcome, how can I help you today?"
          onComplete={this.handleComplete.bind(this)}
          clearOnComplete={true}
          conversationModeOn={false}
          voiceEnabled={true}
          voiceConfig={customVoiceConfig}
        />

 const customVoiceConfig = {
      silenceDetectionConfig: {
          time: 2000,
          amplitude: 0.2
      }   
  }
I am following this link : https://aws-amplify.github.io/docs/js/interactions

    While using voice enabled interaction I am getting this error. When I press the voice button.

    [enter image description here][1]Aws_restJson1_1.ts:834 Uncaught (in promise) **BadRequestException: Invalid Request: The header x-amz-content-sha256 must be set to the literal string** UNSIGNED-PAYLOAD.
        at http://localhost:3000/static/js/1.chunk.js:91237:42
        at step (http://localhost:3000/static/js/1.chunk.js:318206:17)
        at Object.next (http://localhost:3000/static/js/1.chunk.js:318137:14)
        at fulfilled (http://localhost:3000/static/js/1.chunk.js:318092:24)

      [1]: https://i.stack.imgur.com/4heUC.png
Can anyone help me to figure out this issue.

**Comment by Gingonic** [comment]
@rushesh Did you manage to find a workaround on this?

**Comment by kkrzyzek** [comment]
@rushesh @Gingonic facing same issues. Have you been able to solve it guys?

**Comment by kkrzyzek** [comment]
@Gingonic FYI: I've opened an issue for aws-sdk related to this problem: https://github.com/aws/aws-sdk-js-v3/issues/1125
I believe the lib needs to be adjusted.

**Comment by rushesh** [comment]
@Gingonic @kkrzyzek 
No,
I had to change to build a bot using amplify interaction and that bot only working that too using react.js and not in angularjs.

**Comment by kkrzyzek** [comment]
@rushesh got it. Are you using Chatbot UI component provided by Amplify or created your own, custom one?
For me it all started working once I made locally a change, which I mentioned in https://github.com/aws/aws-sdk-js-v3/issues/1125 in my project's node-modules/@aws-sdk

**Comment by rushesh** [comment]
@Gingonic I am using Chatbot UI component provided by Amplify.

**Comment by shresthapradip** [comment]
Still happening. Any workaround or update?
