### ISSUE TITLE
Demo application User Sign-In fails 

### ISSUE THREAD

**Issue by rrrix** [aws-samples/create-react-app-auth-amplify#7]
Hey @swaminator, @dabit3, 

Using the link in this repositories [README.md](https://github.com/aws-samples/create-react-app-auth-amplify/blob/master/README.md) for [View demo](https://master.d2ka7y7551sk8n.amplifyapp.com/):

When trying to create a new account, no matter what I enter in Username / Email / Password / Phone, it shows an error `User does not exist` in a modal at the top of the window:

![image](https://user-images.githubusercontent.com/3194704/70943017-b8c38200-2004-11ea-9dfd-fbf6ae2805c2.png)

I haven't tried deploying this to an AWS environment myself yet - I wanted to see what the experience was like before doing so.

**Comment by Tayman1** [comment]
I am having the same issue.
